/**
 * @fileoverview gRPC-Web generated client stub for smpl.time.api.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: time.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.smpl = {};
proto.smpl.time = {};
proto.smpl.time.api = {};
proto.smpl.time.api.v1 = require('./time_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.smpl.time.api.v1.TimeServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.smpl.time.api.v1.TimeServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.smpl.time.api.v1.GetCurrentTimeRequest,
 *   !proto.smpl.time.api.v1.GetCurrentTimeResponse>}
 */
const methodDescriptor_TimeService_GetCurrentTime = new grpc.web.MethodDescriptor(
  '/smpl.time.api.v1.TimeService/GetCurrentTime',
  grpc.web.MethodType.UNARY,
  proto.smpl.time.api.v1.GetCurrentTimeRequest,
  proto.smpl.time.api.v1.GetCurrentTimeResponse,
  /**
   * @param {!proto.smpl.time.api.v1.GetCurrentTimeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.smpl.time.api.v1.GetCurrentTimeResponse.deserializeBinary
);


/**
 * @param {!proto.smpl.time.api.v1.GetCurrentTimeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.smpl.time.api.v1.GetCurrentTimeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.smpl.time.api.v1.GetCurrentTimeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.smpl.time.api.v1.TimeServiceClient.prototype.getCurrentTime =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/smpl.time.api.v1.TimeService/GetCurrentTime',
      request,
      metadata || {},
      methodDescriptor_TimeService_GetCurrentTime,
      callback);
};


/**
 * @param {!proto.smpl.time.api.v1.GetCurrentTimeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.smpl.time.api.v1.GetCurrentTimeResponse>}
 *     Promise that resolves to the response
 */
proto.smpl.time.api.v1.TimeServicePromiseClient.prototype.getCurrentTime =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/smpl.time.api.v1.TimeService/GetCurrentTime',
      request,
      metadata || {},
      methodDescriptor_TimeService_GetCurrentTime);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.smpl.time.api.v1.GetGreetRequest,
 *   !proto.smpl.time.api.v1.GetGreetResponse>}
 */
const methodDescriptor_TimeService_GetGreet = new grpc.web.MethodDescriptor(
  '/smpl.time.api.v1.TimeService/GetGreet',
  grpc.web.MethodType.UNARY,
  proto.smpl.time.api.v1.GetGreetRequest,
  proto.smpl.time.api.v1.GetGreetResponse,
  /**
   * @param {!proto.smpl.time.api.v1.GetGreetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.smpl.time.api.v1.GetGreetResponse.deserializeBinary
);


/**
 * @param {!proto.smpl.time.api.v1.GetGreetRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.smpl.time.api.v1.GetGreetResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.smpl.time.api.v1.GetGreetResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.smpl.time.api.v1.TimeServiceClient.prototype.getGreet =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/smpl.time.api.v1.TimeService/GetGreet',
      request,
      metadata || {},
      methodDescriptor_TimeService_GetGreet,
      callback);
};


/**
 * @param {!proto.smpl.time.api.v1.GetGreetRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.smpl.time.api.v1.GetGreetResponse>}
 *     Promise that resolves to the response
 */
proto.smpl.time.api.v1.TimeServicePromiseClient.prototype.getGreet =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/smpl.time.api.v1.TimeService/GetGreet',
      request,
      metadata || {},
      methodDescriptor_TimeService_GetGreet);
};


module.exports = proto.smpl.time.api.v1;

